# Generated by Django 5.2.4 on 2025-11-06 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
        migrations.DeleteModel(
            name='LoginHistory',
        ),
    ]
