# Generated by Django 5.2.4 on 2025-11-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='food',
            new_name='vision_food_name_c04551_idx',
            old_name='vision_food_name_idx',
        ),
        migrations.RenameIndex(
            model_name='foodlog',
            new_name='vision_food_user_id_ff7132_idx',
            old_name='vision_foodlog_user_logged_idx',
        ),
        migrations.RenameIndex(
            model_name='foodrecognitionlog',
            new_name='vision_food_user_id_87c558_idx',
            old_name='vision_recog_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='foodrecognitionlog',
            new_name='vision_food_image_s_e4dccd_idx',
            old_name='vision_recog_image_sha_idx',
        ),
        migrations.RenameIndex(
            model_name='pregnancystage',
            new_name='vision_preg_start_w_8b650c_idx',
            old_name='vision_stage_week_idx',
        ),
    ]
